### PR TITLE
vagrant: add collectd and receiver-mock

### PR DESCRIPTION
**Pull request by sumo-drosiek**

### CODE REVIEW

**Review by kkujawa-sumo — APPROVED** [review]

**Comment by pmalek-sumo** [comment]
All the tests are failing 😱

**Comment by sumo-drosiek** [comment]
working on that

**Comment by sumo-drosiek** [comment]
@pmalek-sumo fixed :tired_face:

**Comment by sumo-drosiek** [comment]
I'm going to fix pylint issues in separate PR

**Review by pmalek-sumo — APPROVED** [review]

**Pull request merged**
